name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build:prod

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t yogi109/movie-store:latest

      - name: Push Docker image
        run: docker push yogi109/movie-store:latest

      - name: Start application in the background
        run: docker run -d --name movie-store -p 3000:3000 yogi109/movie-store:latest

      - name: Verify container is running
        run: docker ps -a

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Stop and remove the application container
        run: |
          docker stop movie-store
          docker rm movie-store

      - name: Verify container is stopped and removed
        run: docker ps -a
